### ISSUE TITLE
Add Quiet Option for Grunt Log Messages

### ISSUE THREAD

**Issue by aleveillee** [gruntjs/grunt-contrib-csslint#52]
Similar to the `--quiet` option already available with the CSSLint CLI, I would like a `quiet` option added to the Grunt plugin. When enabled, I expect any warning messages to be hidden and only errors to be shown. I have tried including a `"quiet": true` option in the `.csslintrc` configuration with no luck. I believe adding a simple check around the message statements would suffice:

##### csslint.js #83-90 @ 0.3.1
```javascript
...

if( !options.quiet || ( options.quiet && message.type === "error" )) {
  grunt.log.writeln(chalk.red('[') + offenderMessage + chalk.red(']'));
  grunt.log[ message.type === 'error' ? 'error' : 'writeln' ](
    message.type.toUpperCase() + ': ' +
    message.message + ' ' +
    message.rule.desc +
    ' (' + message.rule.id + ')' +
    ' Browsers: ' + message.rule.browsers
  );
}

...
```

**PS:** I am new to Grunt and new to submitting issues on GitHub so I apologize in advance if this is not the proper place to make these requests. Let me know if you have any questions or suggestions. Thanks.

Anthony

**Comment by hiulit** [comment]
+1
