### ISSUE TITLE
Outlines should only be modified using :focus?

### ISSUE THREAD

**Issue by beautifulcoder** [gruntjs/grunt-contrib-csslint#62]
I have this CSS:

    input[type=text]:invalid, input[type=password]:invalid, textarea:invalid {
        outline: none;
        box-shadow: none;
    }

Unfortunately, in IE I have to set the outline to none and in Firefox I have to set the box-shadow to none. This is a result of adding the `required` attribute to the input tags. In both browsers you get annoying outlines by default. Is this something we've thought about before? It seems `:invalid` should also get considered as a `:focus`.

**Comment by alundiak** [comment]
I have the same, regarding outline. Currently just suppresed by false.

Any update son this issue? It's 22days ago created.

**Comment by vladikoff** [comment]
This bug is for CSSLint itself probably https://github.com/CSSLint/csslint

**Comment by beautifulcoder** [comment]
Moved the issue to: https://github.com/CSSLint/csslint/issues/623
