### ISSUE TITLE
.csslintrc and comments

### ISSUE THREAD

**Issue by alundiak** [gruntjs/grunt-contrib-csslint#63]
It says on docs that it supports, but it doesn't
```
Running "csslint:strict" (csslint) task
Warning: Unable to parse ".csslintrc" file (Unexpected token /). Use --force to continue.
```
Used example from docs.
Any dieas?

"version": "0.2.0"

In which version have u introduced this:
https://github.com/gruntjs/grunt-contrib-csslint/commit/948a7fc735408ca86619b28f0f617eaacb723d03
?

**Comment by jawshooah** [comment]
![v0.4.0](https://i.imgur.com/LTQmHVD.png)

Note the tag.

**Comment by alundiak** [comment]
Ok. it was quick and stupid from my side.
