### ISSUE TITLE
Print Line and Column in Console

### ISSUE THREAD

**Issue by aamL** [gruntjs/grunt-contrib-csslint#69]
Hello,
the output in the console, shows [General] instead of line and column.

After i looked in to the /tasks/ folder I found there the mistake.
```
if (_.isUndefined(message.line)) {
offenderMessage =
  chalk.yellow('L' + message.line) +
  chalk.red(':') +
  chalk.yellow('C' + message.col);
} else {
  offenderMessage = chalk.yellow('GENERAL');
}
```

Should the if condition be inverted?

The Best,
Kevin

**Comment by vladikoff** [comment]
Fixed in https://github.com/gruntjs/grunt-contrib-csslint/commit/f387bb930609f7462ebfb3f96ff5f36c9c040237
