### ISSUE TITLE
False positive on content: '\\';

### ISSUE THREAD

**Issue by Bharathan** [gruntjs/grunt-contrib-csslint#71]
Linting a CSS file with the below code will give a error. The error is 

ERROR: Unexpected token ''\\';' at line 1465, col 11. This rule looks for recoverable syntax errors. (errors) Browsers: All

    .newsletter ul li:before {
	color: #13aa63;
	content: '\\';
	font-family: 'icomoon';
	font-size: 0.7em;
	margin-left: -30px;
	margin-top: -0.3em;
	position: absolute;
	width: 24px;
    }

Here in the above case \ is considered as escape character.

**Comment by Bharathan** [comment]
Workaround found using 
.on .ffCheckbox:after {
    color: #c70729;
    content: '\005c';
font-family: 'icomoon';
}

**Comment by vladikoff** [comment]
Seems like an upstream csslint issue
